using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.ClassLoadout;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.HUDExtensions;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;

public class HUDExtension__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_HUDExtensions_MissionMultiplayerHUDExtensionVM_Dependency_6_MultiplayerSpectatorHUD__DependendPrefab : Widget
{
	private Widget _widget;

	private ListPanel _widget_0;

	private ListPanel _widget_0_0;

	private Widget _widget_0_0_0;

	private HUDExtension__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_HUDExtensions_MissionMultiplayerHUDExtensionVM_Dependency_10_MultiplayerCompassElement__DependendPrefab _widget_0_0_0_0;

	private TextWidget _widget_0_0_1;

	private ListPanel _widget_0_1;

	private Widget _widget_0_1_0;

	private Widget _widget_0_1_1;

	private SliderWidget _widget_0_1_1_0;

	private Widget _widget_0_1_1_0_0;

	private Widget _widget_0_1_1_0_1;

	private Widget _widget_0_1_2;

	private Widget _widget_0_1_3;

	private SliderWidget _widget_0_1_3_0;

	private Widget _widget_0_1_3_0_0;

	private Widget _widget_0_1_3_0_1;

	private Widget _widget_0_1_4;

	private Widget _widget_0_1_5;

	private SliderWidget _widget_0_1_5_0;

	private Widget _widget_0_1_5_0_0;

	private Widget _widget_0_1_5_0_1;

	private Widget _widget_0_1_6;

	private Widget _widget_0_1_6_0;

	private TextWidget _widget_0_1_7;

	private RichTextWidget _widget_0_2;

	private MissionMultiplayerSpectatorHUDVM _datasource_Root;

	private MPTeammateCompassTargetVM _datasource_Root_CompassElement;

	public HUDExtension__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_HUDExtensions_MissionMultiplayerHUDExtensionVM_Dependency_6_MultiplayerSpectatorHUD__DependendPrefab(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ListPanel(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new ListPanel(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_0_0 = new Widget(base.Context);
		_widget_0_0.AddChild(_widget_0_0_0);
		_widget_0_0_0_0 = new HUDExtension__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_HUDExtensions_MissionMultiplayerHUDExtensionVM_Dependency_10_MultiplayerCompassElement__DependendPrefab(base.Context);
		_widget_0_0_0.AddChild(_widget_0_0_0_0);
		_widget_0_0_0_0.CreateWidgets();
		_widget_0_0_1 = new TextWidget(base.Context);
		_widget_0_0.AddChild(_widget_0_0_1);
		_widget_0_1 = new ListPanel(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_1_0 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_0);
		_widget_0_1_1 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_1);
		_widget_0_1_1_0 = new SliderWidget(base.Context);
		_widget_0_1_1.AddChild(_widget_0_1_1_0);
		_widget_0_1_1_0_0 = new Widget(base.Context);
		_widget_0_1_1_0.AddChild(_widget_0_1_1_0_0);
		_widget_0_1_1_0_1 = new Widget(base.Context);
		_widget_0_1_1_0.AddChild(_widget_0_1_1_0_1);
		_widget_0_1_2 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_2);
		_widget_0_1_3 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_3);
		_widget_0_1_3_0 = new SliderWidget(base.Context);
		_widget_0_1_3.AddChild(_widget_0_1_3_0);
		_widget_0_1_3_0_0 = new Widget(base.Context);
		_widget_0_1_3_0.AddChild(_widget_0_1_3_0_0);
		_widget_0_1_3_0_1 = new Widget(base.Context);
		_widget_0_1_3_0.AddChild(_widget_0_1_3_0_1);
		_widget_0_1_4 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_4);
		_widget_0_1_5 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_5);
		_widget_0_1_5_0 = new SliderWidget(base.Context);
		_widget_0_1_5.AddChild(_widget_0_1_5_0);
		_widget_0_1_5_0_0 = new Widget(base.Context);
		_widget_0_1_5_0.AddChild(_widget_0_1_5_0_0);
		_widget_0_1_5_0_1 = new Widget(base.Context);
		_widget_0_1_5_0.AddChild(_widget_0_1_5_0_1);
		_widget_0_1_6 = new Widget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_6);
		_widget_0_1_6_0 = new Widget(base.Context);
		_widget_0_1_6.AddChild(_widget_0_1_6_0);
		_widget_0_1_7 = new TextWidget(base.Context);
		_widget_0_1.AddChild(_widget_0_1_7);
		_widget_0_2 = new RichTextWidget(base.Context);
		_widget_0.AddChild(_widget_0_2);
	}

	public void SetIds()
	{
		_widget_0_0_0_0.SetIds();
		_widget_0_1_1_0_0.Id = "Filler";
		_widget_0_1_1_0_1.Id = "SliderHandle";
		_widget_0_1_3_0_0.Id = "Filler";
		_widget_0_1_3_0_1.Id = "SliderHandle";
		_widget_0_1_5_0_0.Id = "Filler";
		_widget_0_1_5_0_1.Id = "SliderHandle";
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.CoverChildren;
		base.HeightSizePolicy = SizePolicy.CoverChildren;
		base.HorizontalAlignment = HorizontalAlignment.Center;
		base.VerticalAlignment = VerticalAlignment.Bottom;
		base.MarginBottom = 90f;
		base.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		base.Color = new Color(0f, 0f, 0f, 0.4980392f);
		_widget_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
		_widget_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_0.MarginLeft = 3f;
		_widget_0_0.MarginRight = 3f;
		_widget_0_0.MarginTop = 10f;
		_widget_0_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_0_0.MarginLeft = 3f;
		_widget_0_0_0.MarginRight = 3f;
		_widget_0_0_0_0.SetAttributes();
		_widget_0_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_0_1.MarginLeft = 3f;
		_widget_0_0_1.MarginRight = 3f;
		_widget_0_0_1.Brush = base.Context.GetBrush("MPHUD.SpectatorInfo.Text");
		_widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_1.MarginLeft = 10f;
		_widget_0_1.MarginRight = 10f;
		_widget_0_1.MarginTop = 10f;
		_widget_0_1_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_0.SuggestedWidth = 35f;
		_widget_0_1_0.SuggestedHeight = 35f;
		_widget_0_1_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_0.Sprite = base.Context.SpriteData.GetSprite("General\\Mission\\hero_icon");
		_widget_0_1_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1.SuggestedWidth = 106f;
		_widget_0_1_1.SuggestedHeight = 26f;
		_widget_0_1_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_1.Sprite = base.Context.SpriteData.GetSprite("SelectionBorder@2x_9");
		_widget_0_1_1.ValueFactor = -50f;
		_widget_0_1_1.SaturationFactor = -100f;
		_widget_0_1_1.MarginLeft = 5f;
		_widget_0_1_1_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0.SuggestedWidth = 100f;
		_widget_0_1_1_0.SuggestedHeight = 20f;
		_widget_0_1_1_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_1_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_1_1_0.Filler = _widget_0_1_1_0_0;
		_widget_0_1_1_0.Handle = _widget_0_1_1_0_1;
		_widget_0_1_1_0.Locked = false;
		_widget_0_1_1_0.MinValueFloat = 0f;
		_widget_0_1_1_0_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0_0.SuggestedWidth = 100f;
		_widget_0_1_1_0_0.SuggestedHeight = 20f;
		_widget_0_1_1_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_1_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_1_1_0_0.Color = new Color(0.7686275f, 0.2235294f, 0.1843137f);
		_widget_0_1_1_0_1.DoNotAcceptEvents = true;
		_widget_0_1_1_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_1_0_1.SuggestedWidth = 14f;
		_widget_0_1_1_0_1.SuggestedHeight = 38f;
		_widget_0_1_1_0_1.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_0_1_1_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_1_0_1.IsVisible = false;
		_widget_0_1_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_2.SuggestedWidth = 35f;
		_widget_0_1_2.SuggestedHeight = 35f;
		_widget_0_1_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_2.MarginLeft = 10f;
		_widget_0_1_2.Sprite = base.Context.SpriteData.GetSprite("General\\Mission\\mount_icon");
		_widget_0_1_3.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3.SuggestedWidth = 106f;
		_widget_0_1_3.SuggestedHeight = 26f;
		_widget_0_1_3.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_3.Sprite = base.Context.SpriteData.GetSprite("SelectionBorder@2x_9");
		_widget_0_1_3.ValueFactor = -50f;
		_widget_0_1_3.SaturationFactor = -100f;
		_widget_0_1_3.MarginLeft = 5f;
		_widget_0_1_3_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0.SuggestedWidth = 100f;
		_widget_0_1_3_0.SuggestedHeight = 20f;
		_widget_0_1_3_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_3_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_1_3_0.Filler = _widget_0_1_3_0_0;
		_widget_0_1_3_0.Handle = _widget_0_1_3_0_1;
		_widget_0_1_3_0.Locked = false;
		_widget_0_1_3_0.MinValueInt = 0;
		_widget_0_1_3_0_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0_0.SuggestedWidth = 100f;
		_widget_0_1_3_0_0.SuggestedHeight = 20f;
		_widget_0_1_3_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_3_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_1_3_0_0.Color = new Color(0.7686275f, 0.2235294f, 0.1843137f);
		_widget_0_1_3_0_1.DoNotAcceptEvents = true;
		_widget_0_1_3_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_3_0_1.SuggestedWidth = 14f;
		_widget_0_1_3_0_1.SuggestedHeight = 38f;
		_widget_0_1_3_0_1.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_0_1_3_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_3_0_1.IsVisible = false;
		_widget_0_1_4.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_4.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_4.SuggestedWidth = 35f;
		_widget_0_1_4.SuggestedHeight = 35f;
		_widget_0_1_4.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_4.MarginLeft = 10f;
		_widget_0_1_4.Sprite = base.Context.SpriteData.GetSprite("General\\Mission\\shield_icon");
		_widget_0_1_5.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5.SuggestedWidth = 106f;
		_widget_0_1_5.SuggestedHeight = 26f;
		_widget_0_1_5.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_5.Sprite = base.Context.SpriteData.GetSprite("SelectionBorder@2x_9");
		_widget_0_1_5.ValueFactor = -50f;
		_widget_0_1_5.SaturationFactor = -100f;
		_widget_0_1_5.MarginLeft = 5f;
		_widget_0_1_5_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0.SuggestedWidth = 100f;
		_widget_0_1_5_0.SuggestedHeight = 20f;
		_widget_0_1_5_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_5_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_1_5_0.Filler = _widget_0_1_5_0_0;
		_widget_0_1_5_0.Handle = _widget_0_1_5_0_1;
		_widget_0_1_5_0.Locked = false;
		_widget_0_1_5_0.MinValueInt = 0;
		_widget_0_1_5_0_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0_0.SuggestedWidth = 100f;
		_widget_0_1_5_0_0.SuggestedHeight = 20f;
		_widget_0_1_5_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_5_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_1_5_0_0.Color = new Color(0.9215687f, 0.6352941f, 0.2039216f);
		_widget_0_1_5_0_1.DoNotAcceptEvents = true;
		_widget_0_1_5_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_5_0_1.SuggestedWidth = 14f;
		_widget_0_1_5_0_1.SuggestedHeight = 38f;
		_widget_0_1_5_0_1.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_0_1_5_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_5_0_1.IsVisible = false;
		_widget_0_1_6.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_6.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_6.SuggestedWidth = 35f;
		_widget_0_1_6.SuggestedHeight = 35f;
		_widget_0_1_6.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_6.MarginLeft = 10f;
		_widget_0_1_6_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1_6_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1_6_0.SuggestedWidth = 70f;
		_widget_0_1_6_0.SuggestedHeight = 74f;
		_widget_0_1_6_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_1_6_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_1_6_0.Sprite = base.Context.SpriteData.GetSprite("MPClassLoadout\\ItemIcons\\Ammo");
		_widget_0_1_7.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_1_7.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_2.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_2.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_2.MarginLeft = 10f;
		_widget_0_2.MarginRight = 10f;
		_widget_0_2.MarginTop = 10f;
		_widget_0_2.Brush = base.Context.GetBrush("MPHUD.SpectatorInfo.Text");
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_widget_0_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_4.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_5.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_6.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_7.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
			if (_datasource_Root_CompassElement != null)
			{
				_widget_0_0_0_0.DestroyDataSource();
				_datasource_Root_CompassElement.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(MissionMultiplayerSpectatorHUDVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsSpectatingAgent = _widget.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_0_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasCompassElement = _widget_0_0_0.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_0_1(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.SpectatedPlayerName = _widget_0_0_1.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.ShowAgentHealth = _widget_0_1_0.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.ShowAgentHealth = _widget_0_1_1.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_1_0(string propertyName)
	{
		if (propertyName == "MaxValueFloat")
		{
			_datasource_Root.SpectatedPlayerHealthLimit = _widget_0_1_1_0.MaxValueFloat;
		}
		else if (propertyName == "ValueFloat")
		{
			_datasource_Root.SpectatedPlayerCurrentHealth = _widget_0_1_1_0.ValueFloat;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasMount = _widget_0_1_2.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_3(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasMount = _widget_0_1_3.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_3_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_3_0(string propertyName)
	{
		switch (propertyName)
		{
		case "IsVisible":
			_datasource_Root.AgentHasMount = _widget_0_1_3_0.IsVisible;
			break;
		case "MaxValueFloat":
			_datasource_Root.SpectatedPlayerMountHealthLimit = _widget_0_1_3_0.MaxValueFloat;
			break;
		case "ValueFloat":
			_datasource_Root.SpectatedPlayerMountCurrentHealth = _widget_0_1_3_0.ValueFloat;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_4(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_4(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasShield = _widget_0_1_4.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_5(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasShield = _widget_0_1_5.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_5_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_5_0(string propertyName)
	{
		switch (propertyName)
		{
		case "IsVisible":
			_datasource_Root.AgentHasShield = _widget_0_1_5_0.IsVisible;
			break;
		case "MaxValueFloat":
			_datasource_Root.SpectatedPlayerShieldHealthLimit = _widget_0_1_5_0.MaxValueFloat;
			break;
		case "ValueFloat":
			_datasource_Root.SpectatedPlayerShieldCurrentHealth = _widget_0_1_5_0.ValueFloat;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_6(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_6(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasRangedWeapon = _widget_0_1_6.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_7(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_7(string propertyName)
	{
		if (propertyName == "IntText")
		{
			_datasource_Root.SpectatedPlayerAmmoAmount = _widget_0_1_7.IntText;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root.AgentHasRangedWeapon = _widget_0_1_7.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.CanTakeControlOfSpectatedAgent = _widget_0_2.IsVisible;
		}
		else if (propertyName == "Text")
		{
			_datasource_Root.TakeControlText = _widget_0_2.Text;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "CompassElement":
			RefreshDataSource_datasource_Root_CompassElement(_datasource_Root.CompassElement);
			break;
		case "IsSpectatingAgent":
			_widget.IsVisible = _datasource_Root.IsSpectatingAgent;
			break;
		case "AgentHasCompassElement":
			_widget_0_0_0.IsVisible = _datasource_Root.AgentHasCompassElement;
			break;
		case "SpectatedPlayerName":
			_widget_0_0_1.Text = _datasource_Root.SpectatedPlayerName;
			break;
		case "ShowAgentHealth":
			_widget_0_1_0.IsVisible = _datasource_Root.ShowAgentHealth;
			_widget_0_1_1.IsVisible = _datasource_Root.ShowAgentHealth;
			break;
		case "SpectatedPlayerHealthLimit":
			_widget_0_1_1_0.MaxValueFloat = _datasource_Root.SpectatedPlayerHealthLimit;
			break;
		case "SpectatedPlayerCurrentHealth":
			_widget_0_1_1_0.ValueFloat = _datasource_Root.SpectatedPlayerCurrentHealth;
			break;
		case "AgentHasMount":
			_widget_0_1_2.IsVisible = _datasource_Root.AgentHasMount;
			_widget_0_1_3.IsVisible = _datasource_Root.AgentHasMount;
			_widget_0_1_3_0.IsVisible = _datasource_Root.AgentHasMount;
			break;
		case "SpectatedPlayerMountHealthLimit":
			_widget_0_1_3_0.MaxValueFloat = _datasource_Root.SpectatedPlayerMountHealthLimit;
			break;
		case "SpectatedPlayerMountCurrentHealth":
			_widget_0_1_3_0.ValueFloat = _datasource_Root.SpectatedPlayerMountCurrentHealth;
			break;
		case "AgentHasShield":
			_widget_0_1_4.IsVisible = _datasource_Root.AgentHasShield;
			_widget_0_1_5.IsVisible = _datasource_Root.AgentHasShield;
			_widget_0_1_5_0.IsVisible = _datasource_Root.AgentHasShield;
			break;
		case "SpectatedPlayerShieldHealthLimit":
			_widget_0_1_5_0.MaxValueFloat = _datasource_Root.SpectatedPlayerShieldHealthLimit;
			break;
		case "SpectatedPlayerShieldCurrentHealth":
			_widget_0_1_5_0.ValueFloat = _datasource_Root.SpectatedPlayerShieldCurrentHealth;
			break;
		case "AgentHasRangedWeapon":
			_widget_0_1_6.IsVisible = _datasource_Root.AgentHasRangedWeapon;
			_widget_0_1_7.IsVisible = _datasource_Root.AgentHasRangedWeapon;
			break;
		case "SpectatedPlayerAmmoAmount":
			_widget_0_1_7.IntText = _datasource_Root.SpectatedPlayerAmmoAmount;
			break;
		case "CanTakeControlOfSpectatedAgent":
			_widget_0_2.IsVisible = _datasource_Root.CanTakeControlOfSpectatedAgent;
			break;
		case "TakeControlText":
			_widget_0_2.Text = _datasource_Root.TakeControlText;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_CompassElement(string propertyName)
	{
	}

	private void RefreshDataSource_datasource_Root(MissionMultiplayerSpectatorHUDVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_widget_0_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_4.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_5.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_6.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_7.PropertyChanged -= PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
			if (_datasource_Root_CompassElement != null)
			{
				_widget_0_0_0_0.SetDataSource(null);
				_datasource_Root_CompassElement.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.IsVisible = _datasource_Root.IsSpectatingAgent;
			_widget.PropertyChanged += PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged += intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
			_widget_0_0_0.IsVisible = _datasource_Root.AgentHasCompassElement;
			_widget_0_0_0.PropertyChanged += PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_1.Text = _datasource_Root.SpectatedPlayerName;
			_widget_0_0_1.PropertyChanged += PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_0_1;
			_widget_0_1_0.IsVisible = _datasource_Root.ShowAgentHealth;
			_widget_0_1_0.PropertyChanged += PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_0;
			_widget_0_1_1.IsVisible = _datasource_Root.ShowAgentHealth;
			_widget_0_1_1.PropertyChanged += PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_1;
			_widget_0_1_1_0.MaxValueFloat = _datasource_Root.SpectatedPlayerHealthLimit;
			_widget_0_1_1_0.ValueFloat = _datasource_Root.SpectatedPlayerCurrentHealth;
			_widget_0_1_1_0.PropertyChanged += PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_1_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_1_0;
			_widget_0_1_2.IsVisible = _datasource_Root.AgentHasMount;
			_widget_0_1_2.PropertyChanged += PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_2;
			_widget_0_1_3.IsVisible = _datasource_Root.AgentHasMount;
			_widget_0_1_3.PropertyChanged += PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_3;
			_widget_0_1_3_0.IsVisible = _datasource_Root.AgentHasMount;
			_widget_0_1_3_0.MaxValueFloat = _datasource_Root.SpectatedPlayerMountHealthLimit;
			_widget_0_1_3_0.ValueFloat = _datasource_Root.SpectatedPlayerMountCurrentHealth;
			_widget_0_1_3_0.PropertyChanged += PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_3_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_3_0;
			_widget_0_1_4.IsVisible = _datasource_Root.AgentHasShield;
			_widget_0_1_4.PropertyChanged += PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_4.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_4;
			_widget_0_1_5.IsVisible = _datasource_Root.AgentHasShield;
			_widget_0_1_5.PropertyChanged += PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_5;
			_widget_0_1_5_0.IsVisible = _datasource_Root.AgentHasShield;
			_widget_0_1_5_0.MaxValueFloat = _datasource_Root.SpectatedPlayerShieldHealthLimit;
			_widget_0_1_5_0.ValueFloat = _datasource_Root.SpectatedPlayerShieldCurrentHealth;
			_widget_0_1_5_0.PropertyChanged += PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_5_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_5_0;
			_widget_0_1_6.IsVisible = _datasource_Root.AgentHasRangedWeapon;
			_widget_0_1_6.PropertyChanged += PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_6.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_6;
			_widget_0_1_7.IntText = _datasource_Root.SpectatedPlayerAmmoAmount;
			_widget_0_1_7.IsVisible = _datasource_Root.AgentHasRangedWeapon;
			_widget_0_1_7.PropertyChanged += PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_1_7.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_7;
			_widget_0_2.IsVisible = _datasource_Root.CanTakeControlOfSpectatedAgent;
			_widget_0_2.Text = _datasource_Root.TakeControlText;
			_widget_0_2.PropertyChanged += PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2;
			_datasource_Root_CompassElement = _datasource_Root.CompassElement;
			if (_datasource_Root_CompassElement != null)
			{
				_datasource_Root_CompassElement.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement;
				_datasource_Root_CompassElement.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement;
				_widget_0_0_0_0.SetDataSource(_datasource_Root_CompassElement);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_CompassElement(MPTeammateCompassTargetVM newDataSource)
	{
		if (_datasource_Root_CompassElement != null)
		{
			_widget_0_0_0_0.SetDataSource(null);
			_datasource_Root_CompassElement.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement = null;
		}
		_datasource_Root_CompassElement = newDataSource;
		_datasource_Root_CompassElement = _datasource_Root.CompassElement;
		if (_datasource_Root_CompassElement != null)
		{
			_datasource_Root_CompassElement.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CompassElement;
			_datasource_Root_CompassElement.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CompassElement;
			_widget_0_0_0_0.SetDataSource(_datasource_Root_CompassElement);
		}
	}
}
