using System.Collections;
using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem.Definition;

namespace TaleWorlds.Core;

internal class AutoGeneratedSaveManager : IAutoGeneratedSaveManager
{
	public void Initialize(DefinitionContext definitionContext)
	{
		TypeDefinition obj = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10002));
		CollectObjectsDelegate collectObjectsDelegate = ArmorComponent.AutoGeneratedStaticCollectObjectsArmorComponent;
		obj.InitializeForAutoGeneration(collectObjectsDelegate);
		TypeDefinition obj2 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10003));
		CollectObjectsDelegate collectObjectsDelegate2 = Banner.AutoGeneratedStaticCollectObjectsBanner;
		obj2.InitializeForAutoGeneration(collectObjectsDelegate2);
		obj2.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(Banner.AutoGeneratedGetMemberValue_bannerDataList);
		TypeDefinition obj3 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10004));
		CollectObjectsDelegate collectObjectsDelegate3 = BannerData.AutoGeneratedStaticCollectObjectsBannerData;
		obj3.InitializeForAutoGeneration(collectObjectsDelegate3);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 3)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_colorId2);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 4)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_size);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 5)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_position);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 6)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_drawStroke);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 7)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_mirror);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 8)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_rotationValue);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_meshId);
		obj3.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(BannerData.AutoGeneratedGetMemberValue_colorId);
		TypeDefinition obj4 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10005));
		CollectObjectsDelegate collectObjectsDelegate4 = BasicCharacterObject.AutoGeneratedStaticCollectObjectsBasicCharacterObject;
		obj4.InitializeForAutoGeneration(collectObjectsDelegate4);
		TypeDefinition obj5 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10006));
		CollectObjectsDelegate collectObjectsDelegate5 = CharacterAttribute.AutoGeneratedStaticCollectObjectsCharacterAttribute;
		obj5.InitializeForAutoGeneration(collectObjectsDelegate5);
		TypeDefinition obj6 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10008));
		CollectObjectsDelegate collectObjectsDelegate6 = CharacterSkills.AutoGeneratedStaticCollectObjectsCharacterSkills;
		obj6.InitializeForAutoGeneration(collectObjectsDelegate6);
		TypeDefinition obj7 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10009));
		CollectObjectsDelegate collectObjectsDelegate7 = WeaponDesign.AutoGeneratedStaticCollectObjectsWeaponDesign;
		obj7.InitializeForAutoGeneration(collectObjectsDelegate7);
		obj7.GetPropertyDefinitionWithId(new MemberTypeId(2, 21)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueWeaponName);
		obj7.GetPropertyDefinitionWithId(new MemberTypeId(2, 50)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueHandToBottomLength);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 10)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueWeaponFlags);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 60)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueCraftedWeaponLength);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 70)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueTemplate);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 80)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueTopPivotOffsets);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 90)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueBottomPivotOffsets);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 100)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValueHolsterShiftAmount);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 30)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValue_usedPieces);
		obj7.GetFieldDefinitionWithId(new MemberTypeId(2, 40)).InitializeForAutoGeneration(WeaponDesign.AutoGeneratedGetMemberValue_piecePivotDistances);
		TypeDefinition obj8 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10010));
		CollectObjectsDelegate collectObjectsDelegate8 = CraftingPiece.AutoGeneratedStaticCollectObjectsCraftingPiece;
		obj8.InitializeForAutoGeneration(collectObjectsDelegate8);
		TypeDefinition obj9 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10011));
		CollectObjectsDelegate collectObjectsDelegate9 = CraftingTemplate.AutoGeneratedStaticCollectObjectsCraftingTemplate;
		obj9.InitializeForAutoGeneration(collectObjectsDelegate9);
		_ = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10015));
		TypeDefinition obj10 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10016));
		CollectObjectsDelegate collectObjectsDelegate10 = Equipment.AutoGeneratedStaticCollectObjectsEquipment;
		obj10.InitializeForAutoGeneration(collectObjectsDelegate10);
		obj10.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(Equipment.AutoGeneratedGetMemberValue_equipmentType);
		obj10.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(Equipment.AutoGeneratedGetMemberValue_itemSlots);
		TypeDefinition obj11 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10018));
		CollectObjectsDelegate collectObjectsDelegate11 = TradeItemComponent.AutoGeneratedStaticCollectObjectsTradeItemComponent;
		obj11.InitializeForAutoGeneration(collectObjectsDelegate11);
		_ = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10026));
		TypeDefinition obj12 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10027));
		CollectObjectsDelegate collectObjectsDelegate12 = HorseComponent.AutoGeneratedStaticCollectObjectsHorseComponent;
		obj12.InitializeForAutoGeneration(collectObjectsDelegate12);
		TypeDefinition obj13 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10028));
		CollectObjectsDelegate collectObjectsDelegate13 = ItemCategory.AutoGeneratedStaticCollectObjectsItemCategory;
		obj13.InitializeForAutoGeneration(collectObjectsDelegate13);
		_ = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10029));
		TypeDefinition obj14 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10030));
		CollectObjectsDelegate collectObjectsDelegate14 = ItemModifier.AutoGeneratedStaticCollectObjectsItemModifier;
		obj14.InitializeForAutoGeneration(collectObjectsDelegate14);
		TypeDefinition obj15 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10031));
		CollectObjectsDelegate collectObjectsDelegate15 = ItemModifierGroup.AutoGeneratedStaticCollectObjectsItemModifierGroup;
		obj15.InitializeForAutoGeneration(collectObjectsDelegate15);
		TypeDefinition obj16 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10032));
		CollectObjectsDelegate collectObjectsDelegate16 = ItemObject.AutoGeneratedStaticCollectObjectsItemObject;
		obj16.InitializeForAutoGeneration(collectObjectsDelegate16);
		TypeDefinition obj17 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10036));
		CollectObjectsDelegate collectObjectsDelegate17 = MissionResult.AutoGeneratedStaticCollectObjectsMissionResult;
		obj17.InitializeForAutoGeneration(collectObjectsDelegate17);
		TypeDefinition obj18 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10038));
		CollectObjectsDelegate collectObjectsDelegate18 = PropertyObject.AutoGeneratedStaticCollectObjectsPropertyObject;
		obj18.InitializeForAutoGeneration(collectObjectsDelegate18);
		TypeDefinition obj19 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10039));
		CollectObjectsDelegate collectObjectsDelegate19 = SkillObject.AutoGeneratedStaticCollectObjectsSkillObject;
		obj19.InitializeForAutoGeneration(collectObjectsDelegate19);
		_ = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10040));
		_ = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10041));
		TypeDefinition obj20 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10042));
		CollectObjectsDelegate collectObjectsDelegate20 = SiegeEngineType.AutoGeneratedStaticCollectObjectsSiegeEngineType;
		obj20.InitializeForAutoGeneration(collectObjectsDelegate20);
		TypeDefinition obj21 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10044));
		CollectObjectsDelegate collectObjectsDelegate21 = WeaponDesignElement.AutoGeneratedStaticCollectObjectsWeaponDesignElement;
		obj21.InitializeForAutoGeneration(collectObjectsDelegate21);
		obj21.GetFieldDefinitionWithId(new MemberTypeId(2, 10)).InitializeForAutoGeneration(WeaponDesignElement.AutoGeneratedGetMemberValue_craftingPiece);
		obj21.GetFieldDefinitionWithId(new MemberTypeId(2, 20)).InitializeForAutoGeneration(WeaponDesignElement.AutoGeneratedGetMemberValue_scalePercentage);
		TypeDefinition obj22 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10045));
		CollectObjectsDelegate collectObjectsDelegate22 = WeaponComponent.AutoGeneratedStaticCollectObjectsWeaponComponent;
		obj22.InitializeForAutoGeneration(collectObjectsDelegate22);
		TypeDefinition obj23 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10046));
		CollectObjectsDelegate collectObjectsDelegate23 = WeaponComponentData.AutoGeneratedStaticCollectObjectsWeaponComponentData;
		obj23.InitializeForAutoGeneration(collectObjectsDelegate23);
		((TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10050))).GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(InformationData.AutoGeneratedGetMemberValueDescriptionText);
		TypeDefinition obj24 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10052));
		CollectObjectsDelegate collectObjectsDelegate24 = MBFastRandom.AutoGeneratedStaticCollectObjectsMBFastRandom;
		obj24.InitializeForAutoGeneration(collectObjectsDelegate24);
		obj24.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(MBFastRandom.AutoGeneratedGetMemberValue_x);
		obj24.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(MBFastRandom.AutoGeneratedGetMemberValue_y);
		obj24.GetFieldDefinitionWithId(new MemberTypeId(2, 3)).InitializeForAutoGeneration(MBFastRandom.AutoGeneratedGetMemberValue_z);
		obj24.GetFieldDefinitionWithId(new MemberTypeId(2, 4)).InitializeForAutoGeneration(MBFastRandom.AutoGeneratedGetMemberValue_w);
		TypeDefinition obj25 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10053));
		CollectObjectsDelegate collectObjectsDelegate25 = BannerComponent.AutoGeneratedStaticCollectObjectsBannerComponent;
		obj25.InitializeForAutoGeneration(collectObjectsDelegate25);
		TypeDefinition obj26 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11004));
		CollectObjectsDelegate collectObjectsDelegate26 = ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement;
		obj26.InitializeForAutoGeneration(collectObjectsDelegate26);
		obj26.GetPropertyDefinitionWithId(new MemberTypeId(1, 21)).InitializeForAutoGeneration(ItemRosterElement.AutoGeneratedGetMemberValueEquipmentElement);
		obj26.GetFieldDefinitionWithId(new MemberTypeId(1, 11)).InitializeForAutoGeneration(ItemRosterElement.AutoGeneratedGetMemberValue_amount);
		TypeDefinition obj27 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11006));
		CollectObjectsDelegate collectObjectsDelegate27 = UniqueTroopDescriptor.AutoGeneratedStaticCollectObjectsUniqueTroopDescriptor;
		obj27.InitializeForAutoGeneration(collectObjectsDelegate27);
		obj27.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(UniqueTroopDescriptor.AutoGeneratedGetMemberValueUniqueSeed);
		TypeDefinition obj28 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11009));
		CollectObjectsDelegate collectObjectsDelegate28 = StaticBodyProperties.AutoGeneratedStaticCollectObjectsStaticBodyProperties;
		obj28.InitializeForAutoGeneration(collectObjectsDelegate28);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart1);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 2)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart2);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 3)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart3);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 4)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart4);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 5)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart5);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 6)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart6);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 7)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart7);
		obj28.GetPropertyDefinitionWithId(new MemberTypeId(1, 8)).InitializeForAutoGeneration(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart8);
		TypeDefinition obj29 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11011));
		CollectObjectsDelegate collectObjectsDelegate29 = EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement;
		obj29.InitializeForAutoGeneration(collectObjectsDelegate29);
		obj29.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(EquipmentElement.AutoGeneratedGetMemberValueItem);
		obj29.GetPropertyDefinitionWithId(new MemberTypeId(1, 2)).InitializeForAutoGeneration(EquipmentElement.AutoGeneratedGetMemberValueItemModifier);
		obj29.GetPropertyDefinitionWithId(new MemberTypeId(1, 3)).InitializeForAutoGeneration(EquipmentElement.AutoGeneratedGetMemberValueIsQuestItem);
		SaveId saveId = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 11004 "));
		ContainerDefinition obj30 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId);
		CollectObjectsDelegate collectObjectsDelegate30 = AutoGeneratedStaticCollectObjectsForArray0;
		obj30.InitializeForAutoGeneration(collectObjectsDelegate30, hasNoChildObject: false);
		SaveId saveId2 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 11011 "));
		ContainerDefinition obj31 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId2);
		CollectObjectsDelegate collectObjectsDelegate31 = AutoGeneratedStaticCollectObjectsForArray1;
		obj31.InitializeForAutoGeneration(collectObjectsDelegate31, hasNoChildObject: false);
		SaveId saveId3 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 10016 "));
		ContainerDefinition obj32 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId3);
		CollectObjectsDelegate collectObjectsDelegate32 = AutoGeneratedStaticCollectObjectsForArray2;
		obj32.InitializeForAutoGeneration(collectObjectsDelegate32, hasNoChildObject: false);
		SaveId saveId4 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 10044 "));
		ContainerDefinition obj33 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId4);
		CollectObjectsDelegate collectObjectsDelegate33 = AutoGeneratedStaticCollectObjectsForArray3;
		obj33.InitializeForAutoGeneration(collectObjectsDelegate33, hasNoChildObject: false);
		SaveId saveId5 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10032 "));
		ContainerDefinition obj34 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId5);
		CollectObjectsDelegate collectObjectsDelegate34 = AutoGeneratedStaticCollectObjectsForList4;
		obj34.InitializeForAutoGeneration(collectObjectsDelegate34, hasNoChildObject: false);
		SaveId saveId6 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10032 "));
		ContainerDefinition obj35 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId6);
		CollectObjectsDelegate collectObjectsDelegate35 = AutoGeneratedStaticCollectObjectsForList5;
		obj35.InitializeForAutoGeneration(collectObjectsDelegate35, hasNoChildObject: false);
		SaveId saveId7 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10032 "));
		ContainerDefinition obj36 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId7);
		CollectObjectsDelegate collectObjectsDelegate36 = AutoGeneratedStaticCollectObjectsForList6;
		obj36.InitializeForAutoGeneration(collectObjectsDelegate36, hasNoChildObject: false);
		SaveId saveId8 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10029 "));
		ContainerDefinition obj37 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId8);
		CollectObjectsDelegate collectObjectsDelegate37 = AutoGeneratedStaticCollectObjectsForList7;
		obj37.InitializeForAutoGeneration(collectObjectsDelegate37, hasNoChildObject: false);
		SaveId saveId9 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10029 "));
		ContainerDefinition obj38 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId9);
		CollectObjectsDelegate collectObjectsDelegate38 = AutoGeneratedStaticCollectObjectsForList8;
		obj38.InitializeForAutoGeneration(collectObjectsDelegate38, hasNoChildObject: false);
		SaveId saveId10 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10029 "));
		ContainerDefinition obj39 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId10);
		CollectObjectsDelegate collectObjectsDelegate39 = AutoGeneratedStaticCollectObjectsForList9;
		obj39.InitializeForAutoGeneration(collectObjectsDelegate39, hasNoChildObject: false);
		SaveId saveId11 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10030 "));
		ContainerDefinition obj40 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId11);
		CollectObjectsDelegate collectObjectsDelegate40 = AutoGeneratedStaticCollectObjectsForList10;
		obj40.InitializeForAutoGeneration(collectObjectsDelegate40, hasNoChildObject: false);
		SaveId saveId12 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10030 "));
		ContainerDefinition obj41 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId12);
		CollectObjectsDelegate collectObjectsDelegate41 = AutoGeneratedStaticCollectObjectsForList11;
		obj41.InitializeForAutoGeneration(collectObjectsDelegate41, hasNoChildObject: false);
		SaveId saveId13 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10030 "));
		ContainerDefinition obj42 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId13);
		CollectObjectsDelegate collectObjectsDelegate42 = AutoGeneratedStaticCollectObjectsForList12;
		obj42.InitializeForAutoGeneration(collectObjectsDelegate42, hasNoChildObject: false);
		SaveId saveId14 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10031 "));
		ContainerDefinition obj43 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId14);
		CollectObjectsDelegate collectObjectsDelegate43 = AutoGeneratedStaticCollectObjectsForList13;
		obj43.InitializeForAutoGeneration(collectObjectsDelegate43, hasNoChildObject: false);
		SaveId saveId15 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10031 "));
		ContainerDefinition obj44 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId15);
		CollectObjectsDelegate collectObjectsDelegate44 = AutoGeneratedStaticCollectObjectsForList14;
		obj44.InitializeForAutoGeneration(collectObjectsDelegate44, hasNoChildObject: false);
		SaveId saveId16 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10031 "));
		ContainerDefinition obj45 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId16);
		CollectObjectsDelegate collectObjectsDelegate45 = AutoGeneratedStaticCollectObjectsForList15;
		obj45.InitializeForAutoGeneration(collectObjectsDelegate45, hasNoChildObject: false);
		SaveId saveId17 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10006 "));
		ContainerDefinition obj46 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId17);
		CollectObjectsDelegate collectObjectsDelegate46 = AutoGeneratedStaticCollectObjectsForList16;
		obj46.InitializeForAutoGeneration(collectObjectsDelegate46, hasNoChildObject: false);
		SaveId saveId18 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10006 "));
		ContainerDefinition obj47 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId18);
		CollectObjectsDelegate collectObjectsDelegate47 = AutoGeneratedStaticCollectObjectsForList17;
		obj47.InitializeForAutoGeneration(collectObjectsDelegate47, hasNoChildObject: false);
		SaveId saveId19 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10006 "));
		ContainerDefinition obj48 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId19);
		CollectObjectsDelegate collectObjectsDelegate48 = AutoGeneratedStaticCollectObjectsForList18;
		obj48.InitializeForAutoGeneration(collectObjectsDelegate48, hasNoChildObject: false);
		SaveId saveId20 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10039 "));
		ContainerDefinition obj49 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId20);
		CollectObjectsDelegate collectObjectsDelegate49 = AutoGeneratedStaticCollectObjectsForList19;
		obj49.InitializeForAutoGeneration(collectObjectsDelegate49, hasNoChildObject: false);
		SaveId saveId21 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10039 "));
		ContainerDefinition obj50 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId21);
		CollectObjectsDelegate collectObjectsDelegate50 = AutoGeneratedStaticCollectObjectsForList20;
		obj50.InitializeForAutoGeneration(collectObjectsDelegate50, hasNoChildObject: false);
		SaveId saveId22 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10039 "));
		ContainerDefinition obj51 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId22);
		CollectObjectsDelegate collectObjectsDelegate51 = AutoGeneratedStaticCollectObjectsForList21;
		obj51.InitializeForAutoGeneration(collectObjectsDelegate51, hasNoChildObject: false);
		SaveId saveId23 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10028 "));
		ContainerDefinition obj52 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId23);
		CollectObjectsDelegate collectObjectsDelegate52 = AutoGeneratedStaticCollectObjectsForList22;
		obj52.InitializeForAutoGeneration(collectObjectsDelegate52, hasNoChildObject: false);
		SaveId saveId24 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10028 "));
		ContainerDefinition obj53 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId24);
		CollectObjectsDelegate collectObjectsDelegate53 = AutoGeneratedStaticCollectObjectsForList23;
		obj53.InitializeForAutoGeneration(collectObjectsDelegate53, hasNoChildObject: false);
		SaveId saveId25 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10028 "));
		ContainerDefinition obj54 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId25);
		CollectObjectsDelegate collectObjectsDelegate54 = AutoGeneratedStaticCollectObjectsForList24;
		obj54.InitializeForAutoGeneration(collectObjectsDelegate54, hasNoChildObject: false);
		SaveId saveId26 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10010 "));
		ContainerDefinition obj55 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId26);
		CollectObjectsDelegate collectObjectsDelegate55 = AutoGeneratedStaticCollectObjectsForList25;
		obj55.InitializeForAutoGeneration(collectObjectsDelegate55, hasNoChildObject: false);
		SaveId saveId27 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10010 "));
		ContainerDefinition obj56 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId27);
		CollectObjectsDelegate collectObjectsDelegate56 = AutoGeneratedStaticCollectObjectsForList26;
		obj56.InitializeForAutoGeneration(collectObjectsDelegate56, hasNoChildObject: false);
		SaveId saveId28 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10010 "));
		ContainerDefinition obj57 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId28);
		CollectObjectsDelegate collectObjectsDelegate57 = AutoGeneratedStaticCollectObjectsForList27;
		obj57.InitializeForAutoGeneration(collectObjectsDelegate57, hasNoChildObject: false);
		SaveId saveId29 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10011 "));
		ContainerDefinition obj58 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId29);
		CollectObjectsDelegate collectObjectsDelegate58 = AutoGeneratedStaticCollectObjectsForList28;
		obj58.InitializeForAutoGeneration(collectObjectsDelegate58, hasNoChildObject: false);
		SaveId saveId30 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10011 "));
		ContainerDefinition obj59 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId30);
		CollectObjectsDelegate collectObjectsDelegate59 = AutoGeneratedStaticCollectObjectsForList29;
		obj59.InitializeForAutoGeneration(collectObjectsDelegate59, hasNoChildObject: false);
		SaveId saveId31 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10011 "));
		ContainerDefinition obj60 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId31);
		CollectObjectsDelegate collectObjectsDelegate60 = AutoGeneratedStaticCollectObjectsForList30;
		obj60.InitializeForAutoGeneration(collectObjectsDelegate60, hasNoChildObject: false);
		SaveId saveId32 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10042 "));
		ContainerDefinition obj61 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId32);
		CollectObjectsDelegate collectObjectsDelegate61 = AutoGeneratedStaticCollectObjectsForList31;
		obj61.InitializeForAutoGeneration(collectObjectsDelegate61, hasNoChildObject: false);
		SaveId saveId33 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10042 "));
		ContainerDefinition obj62 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId33);
		CollectObjectsDelegate collectObjectsDelegate62 = AutoGeneratedStaticCollectObjectsForList32;
		obj62.InitializeForAutoGeneration(collectObjectsDelegate62, hasNoChildObject: false);
		SaveId saveId34 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10042 "));
		ContainerDefinition obj63 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId34);
		CollectObjectsDelegate collectObjectsDelegate63 = AutoGeneratedStaticCollectObjectsForList33;
		obj63.InitializeForAutoGeneration(collectObjectsDelegate63, hasNoChildObject: false);
		SaveId saveId35 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10038 "));
		ContainerDefinition obj64 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId35);
		CollectObjectsDelegate collectObjectsDelegate64 = AutoGeneratedStaticCollectObjectsForList34;
		obj64.InitializeForAutoGeneration(collectObjectsDelegate64, hasNoChildObject: false);
		SaveId saveId36 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10038 "));
		ContainerDefinition obj65 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId36);
		CollectObjectsDelegate collectObjectsDelegate65 = AutoGeneratedStaticCollectObjectsForList35;
		obj65.InitializeForAutoGeneration(collectObjectsDelegate65, hasNoChildObject: false);
		SaveId saveId37 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10038 "));
		ContainerDefinition obj66 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId37);
		CollectObjectsDelegate collectObjectsDelegate66 = AutoGeneratedStaticCollectObjectsForList36;
		obj66.InitializeForAutoGeneration(collectObjectsDelegate66, hasNoChildObject: false);
		SaveId saveId38 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11006 "));
		ContainerDefinition obj67 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId38);
		CollectObjectsDelegate collectObjectsDelegate67 = AutoGeneratedStaticCollectObjectsForList37;
		obj67.InitializeForAutoGeneration(collectObjectsDelegate67, hasNoChildObject: true);
		SaveId saveId39 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11006 "));
		ContainerDefinition obj68 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId39);
		CollectObjectsDelegate collectObjectsDelegate68 = AutoGeneratedStaticCollectObjectsForList38;
		obj68.InitializeForAutoGeneration(collectObjectsDelegate68, hasNoChildObject: true);
		SaveId saveId40 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11006 "));
		ContainerDefinition obj69 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId40);
		CollectObjectsDelegate collectObjectsDelegate69 = AutoGeneratedStaticCollectObjectsForList39;
		obj69.InitializeForAutoGeneration(collectObjectsDelegate69, hasNoChildObject: true);
		SaveId saveId41 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10016 "));
		ContainerDefinition obj70 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId41);
		CollectObjectsDelegate collectObjectsDelegate70 = AutoGeneratedStaticCollectObjectsForList40;
		obj70.InitializeForAutoGeneration(collectObjectsDelegate70, hasNoChildObject: false);
		SaveId saveId42 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10016 "));
		ContainerDefinition obj71 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId42);
		CollectObjectsDelegate collectObjectsDelegate71 = AutoGeneratedStaticCollectObjectsForList41;
		obj71.InitializeForAutoGeneration(collectObjectsDelegate71, hasNoChildObject: false);
		SaveId saveId43 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10016 "));
		ContainerDefinition obj72 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId43);
		CollectObjectsDelegate collectObjectsDelegate72 = AutoGeneratedStaticCollectObjectsForList42;
		obj72.InitializeForAutoGeneration(collectObjectsDelegate72, hasNoChildObject: false);
		SaveId saveId44 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10004 "));
		ContainerDefinition obj73 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId44);
		CollectObjectsDelegate collectObjectsDelegate73 = AutoGeneratedStaticCollectObjectsForList43;
		obj73.InitializeForAutoGeneration(collectObjectsDelegate73, hasNoChildObject: false);
		SaveId saveId45 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10004 "));
		ContainerDefinition obj74 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId45);
		CollectObjectsDelegate collectObjectsDelegate74 = AutoGeneratedStaticCollectObjectsForList44;
		obj74.InitializeForAutoGeneration(collectObjectsDelegate74, hasNoChildObject: false);
		SaveId saveId46 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10004 "));
		ContainerDefinition obj75 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId46);
		CollectObjectsDelegate collectObjectsDelegate75 = AutoGeneratedStaticCollectObjectsForList45;
		obj75.InitializeForAutoGeneration(collectObjectsDelegate75, hasNoChildObject: false);
		SaveId saveId47 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11011 "));
		ContainerDefinition obj76 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId47);
		CollectObjectsDelegate collectObjectsDelegate76 = AutoGeneratedStaticCollectObjectsForList46;
		obj76.InitializeForAutoGeneration(collectObjectsDelegate76, hasNoChildObject: false);
		SaveId saveId48 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11011 "));
		ContainerDefinition obj77 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId48);
		CollectObjectsDelegate collectObjectsDelegate77 = AutoGeneratedStaticCollectObjectsForList47;
		obj77.InitializeForAutoGeneration(collectObjectsDelegate77, hasNoChildObject: false);
		SaveId saveId49 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11011 "));
		ContainerDefinition obj78 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId49);
		CollectObjectsDelegate collectObjectsDelegate78 = AutoGeneratedStaticCollectObjectsForList48;
		obj78.InitializeForAutoGeneration(collectObjectsDelegate78, hasNoChildObject: false);
		SaveId saveId50 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10009 "));
		ContainerDefinition obj79 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId50);
		CollectObjectsDelegate collectObjectsDelegate79 = AutoGeneratedStaticCollectObjectsForList49;
		obj79.InitializeForAutoGeneration(collectObjectsDelegate79, hasNoChildObject: false);
		SaveId saveId51 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10009 "));
		ContainerDefinition obj80 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId51);
		CollectObjectsDelegate collectObjectsDelegate80 = AutoGeneratedStaticCollectObjectsForList50;
		obj80.InitializeForAutoGeneration(collectObjectsDelegate80, hasNoChildObject: false);
		SaveId saveId52 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10009 "));
		ContainerDefinition obj81 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId52);
		CollectObjectsDelegate collectObjectsDelegate81 = AutoGeneratedStaticCollectObjectsForList51;
		obj81.InitializeForAutoGeneration(collectObjectsDelegate81, hasNoChildObject: false);
		SaveId saveId53 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11004 "));
		ContainerDefinition obj82 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId53);
		CollectObjectsDelegate collectObjectsDelegate82 = AutoGeneratedStaticCollectObjectsForList52;
		obj82.InitializeForAutoGeneration(collectObjectsDelegate82, hasNoChildObject: false);
		SaveId saveId54 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11004 "));
		ContainerDefinition obj83 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId54);
		CollectObjectsDelegate collectObjectsDelegate83 = AutoGeneratedStaticCollectObjectsForList53;
		obj83.InitializeForAutoGeneration(collectObjectsDelegate83, hasNoChildObject: false);
		SaveId saveId55 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11004 "));
		ContainerDefinition obj84 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId55);
		CollectObjectsDelegate collectObjectsDelegate84 = AutoGeneratedStaticCollectObjectsForList54;
		obj84.InitializeForAutoGeneration(collectObjectsDelegate84, hasNoChildObject: false);
		SaveId saveId56 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10050 "));
		ContainerDefinition obj85 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId56);
		CollectObjectsDelegate collectObjectsDelegate85 = AutoGeneratedStaticCollectObjectsForList55;
		obj85.InitializeForAutoGeneration(collectObjectsDelegate85, hasNoChildObject: false);
		SaveId saveId57 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10050 "));
		ContainerDefinition obj86 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId57);
		CollectObjectsDelegate collectObjectsDelegate86 = AutoGeneratedStaticCollectObjectsForList56;
		obj86.InitializeForAutoGeneration(collectObjectsDelegate86, hasNoChildObject: false);
		SaveId saveId58 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10050 "));
		ContainerDefinition obj87 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId58);
		CollectObjectsDelegate collectObjectsDelegate87 = AutoGeneratedStaticCollectObjectsForList57;
		obj87.InitializeForAutoGeneration(collectObjectsDelegate87, hasNoChildObject: false);
		SaveId saveId59 = SaveId.ReadSaveIdFrom(new StringReader("2 2 0 11011 0 30001 "));
		ContainerDefinition obj88 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId59);
		CollectObjectsDelegate collectObjectsDelegate88 = AutoGeneratedStaticCollectObjectsForDictionary58;
		obj88.InitializeForAutoGeneration(collectObjectsDelegate88, hasNoChildObject: false);
	}

	private static void AutoGeneratedStaticCollectObjectsForArray0(object o, List<object> collectedObjects)
	{
		ItemRosterElement[] array = (ItemRosterElement[])o;
		for (int i = 0; i < array.Length; i++)
		{
			ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement(array[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForArray1(object o, List<object> collectedObjects)
	{
		EquipmentElement[] array = (EquipmentElement[])o;
		for (int i = 0; i < array.Length; i++)
		{
			EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement(array[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForArray2(object o, List<object> collectedObjects)
	{
		Equipment[] array = (Equipment[])o;
		foreach (Equipment item in array)
		{
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForArray3(object o, List<object> collectedObjects)
	{
		WeaponDesignElement[] array = (WeaponDesignElement[])o;
		foreach (WeaponDesignElement item in array)
		{
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList4(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemObject item = (ItemObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList5(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemObject item = (ItemObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList6(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemObject item = (ItemObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList7(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemComponent item = (ItemComponent)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList8(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemComponent item = (ItemComponent)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList9(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemComponent item = (ItemComponent)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList10(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifier item = (ItemModifier)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList11(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifier item = (ItemModifier)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList12(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifier item = (ItemModifier)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList13(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifierGroup item = (ItemModifierGroup)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList14(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifierGroup item = (ItemModifierGroup)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList15(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemModifierGroup item = (ItemModifierGroup)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList16(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CharacterAttribute item = (CharacterAttribute)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList17(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CharacterAttribute item = (CharacterAttribute)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList18(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CharacterAttribute item = (CharacterAttribute)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList19(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SkillObject item = (SkillObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList20(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SkillObject item = (SkillObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList21(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SkillObject item = (SkillObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList22(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemCategory item = (ItemCategory)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList23(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemCategory item = (ItemCategory)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList24(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemCategory item = (ItemCategory)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList25(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingPiece item = (CraftingPiece)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList26(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingPiece item = (CraftingPiece)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList27(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingPiece item = (CraftingPiece)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList28(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingTemplate item = (CraftingTemplate)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList29(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingTemplate item = (CraftingTemplate)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList30(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			CraftingTemplate item = (CraftingTemplate)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList31(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SiegeEngineType item = (SiegeEngineType)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList32(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SiegeEngineType item = (SiegeEngineType)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList33(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			SiegeEngineType item = (SiegeEngineType)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList34(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			PropertyObject item = (PropertyObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList35(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			PropertyObject item = (PropertyObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList36(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			PropertyObject item = (PropertyObject)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList37(object o, List<object> collectedObjects)
	{
	}

	private static void AutoGeneratedStaticCollectObjectsForList38(object o, List<object> collectedObjects)
	{
	}

	private static void AutoGeneratedStaticCollectObjectsForList39(object o, List<object> collectedObjects)
	{
	}

	private static void AutoGeneratedStaticCollectObjectsForList40(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			Equipment item = (Equipment)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList41(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			Equipment item = (Equipment)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList42(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			Equipment item = (Equipment)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList43(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			BannerData item = (BannerData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList44(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			BannerData item = (BannerData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList45(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			BannerData item = (BannerData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList46(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList47(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList48(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList49(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			WeaponDesign item = (WeaponDesign)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList50(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			WeaponDesign item = (WeaponDesign)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList51(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			WeaponDesign item = (WeaponDesign)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList52(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList53(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList54(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList55(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			InformationData item = (InformationData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList56(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			InformationData item = (InformationData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForList57(object o, List<object> collectedObjects)
	{
		IList list = (IList)o;
		for (int i = 0; i < list.Count; i++)
		{
			InformationData item = (InformationData)list[i];
			collectedObjects.Add(item);
		}
	}

	private static void AutoGeneratedStaticCollectObjectsForDictionary58(object o, List<object> collectedObjects)
	{
		foreach (object key in ((IDictionary)o).Keys)
		{
			EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement(key, collectedObjects);
		}
	}
}
