using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.Core;

public class CharacterAttribute : PropertyObject
{
	private MBList<SkillObject> _skills;

	public MBReadOnlyList<SkillObject> Skills => _skills;

	public TextObject Abbreviation { get; private set; }

	public CharacterAttribute(string stringId)
		: base(stringId)
	{
	}

	internal void AddSkill(SkillObject skillObject)
	{
		_skills.Capacity = _skills.Count + 1;
		_skills.Add(skillObject);
	}

	public void Initialize(TextObject name, TextObject description, TextObject abbreviation)
	{
		Initialize(name, description);
		Abbreviation = abbreviation;
		_skills = new MBList<SkillObject>(0);
		AfterInitialized();
	}

	internal static void AutoGeneratedStaticCollectObjectsCharacterAttribute(object o, List<object> collectedObjects)
	{
		((CharacterAttribute)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}
}
