using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core;

public class PropertyOwner<T> : MBObjectBase where T : MBObjectBase
{
	[SaveableField(10)]
	protected readonly Dictionary<T, int> _attributes;

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(_attributes);
	}

	public PropertyOwner()
	{
		_attributes = new Dictionary<T, int>();
	}

	public PropertyOwner(PropertyOwner<T> propertyOwner)
	{
		_attributes = new Dictionary<T, int>(propertyOwner._attributes);
	}

	public void SetPropertyValue(T attribute, int value)
	{
		if (value != 0)
		{
			_attributes[attribute] = value;
		}
		else if (HasProperty(attribute))
		{
			_attributes.Remove(attribute);
		}
	}

	public int GetPropertyValue(T attribute)
	{
		if (attribute != null)
		{
			if (!_attributes.TryGetValue(attribute, out var value))
			{
				return 0;
			}
			return value;
		}
		Debug.FailedAssert("attribute in GetPropertyValue can not be null!", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.Core\\PropertyOwner.cs", "GetPropertyValue", 52);
		return 0;
	}

	public bool HasProperty(T attribute)
	{
		return _attributes.ContainsKey(attribute);
	}

	public void ClearAllProperty()
	{
		_attributes.Clear();
	}

	public void Serialize(XmlWriter writer)
	{
		writer.WriteStartElement("attributes");
		foreach (KeyValuePair<T, int> attribute in _attributes)
		{
			writer.WriteStartElement("attribute");
			writer.WriteAttributeString("id", attribute.Key.StringId);
			writer.WriteAttributeString("value", attribute.Value.ToString());
			writer.WriteEndElement();
		}
		writer.WriteEndElement();
	}

	public override void Deserialize(MBObjectManager objectManager, XmlNode node)
	{
		Initialize();
		foreach (XmlNode childNode in node.ChildNodes)
		{
			if (!(childNode.Name == "attributes"))
			{
				continue;
			}
			foreach (XmlNode childNode2 in childNode.ChildNodes)
			{
				if (childNode2.Name == "attribute")
				{
					string innerText = childNode2.Attributes["id"].InnerText;
					if (innerText.Substring(0, innerText.IndexOf('.')).Equals("Attrib"))
					{
						T attribute = objectManager.ReadObjectReferenceFromXml("id", typeof(T), childNode2) as T;
						int value = Convert.ToInt32(childNode2.Attributes["value"].Value);
						SetPropertyValue(attribute, value);
					}
				}
			}
		}
	}
}
